##################################################################################
#
# Bank QrCode Formatter
#
# @package   MarcinOrlowski\QrcodeFormatter
#
# @author    Marcin Orlowski <mail (#) marcinOrlowski (.) com>
# @copyright 2020 Marcin Orlowski
# @license   http://www.opensource.org/licenses/mit-license.php MIT
# @link      https://github.com/MarcinOrlowski/bank-qrcode-formatter
#
##################################################################################

filter:
  excluded_paths: [tests/*]
checks:
  php:
    code_rating: true
    remove_php_closing_tag: true
    remove_trailing_whitespace: true
    fix_use_statements:
      remove_unused: true
      preserve_multiple: false
      preserve_blanklines: true
      order_alphabetically: true
    fix_php_opening_tag: true
    fix_linefeed: true
    fix_line_ending: true
tools:
  external_code_coverage: true
