##################################################################################
#
# Bank QrCode Formatter
#
# @package   MarcinOrlowski\QrcodeFormatter
#
# @author    Marcin Orlowski <mail (#) marcinOrlowski (.) com>
# @copyright 2020 Marcin Orlowski
# @license   http://www.opensource.org/licenses/mit-license.php MIT
# @link      https://github.com/MarcinOrlowski/bank-qrcode-formatter
#
##################################################################################

language: php
dist: trusty

php:
  - 5.4
  - 5.6
  - 7.2
  - 7.3
  - 7.4

cache:
  directories:
    - ${HOME}/.composer/cache/files

before_script:
  #- cp -f "travis/composer-laravel-${LARAVEL_VERSION}.json" composer.json
  - composer install --prefer-dist
  # Need to tweak signature of setUp() and tearDown() methods and strip the ": void" from it, otherwise tests
  # run will fail due to signature mismatch. This affects Laravel 5.8+ and 6.x as they pull recent Orchestra
  # version that features methods' signature change.
  #- "sed -i 's/): void/)/' vendor/orchestra/testbench-core/src/TestCase.php"
  #- "sed -i 's/): void/)/' vendor/phpunit/phpunit/src/Framework/TestCase.php"

script:
  - vendor/bin/phpunit --configuration phpunit.xml --coverage-clover /tmp/clover.xml

#after_success:
  # If coverage file is generated then upload it to Codacy (requires CODACY_PROJECT_TOKEN= env var set).
  #- bash <(wget -q -O - https://coverage.codacy.com/get.sh) report -l PHP -r /tmp/clover.xml
  # Scrutinizer-CI
  #- wget --output-document=/tmp/ocular.phar https://scrutinizer-ci.com/ocular.phar && php /tmp/ocular.phar code-coverage:upload --format=php-clover /tmp/clover.xml
